### ISSUE TITLE
building on existing project

### ISSUE THREAD

**Issue by AmelieA** [unbornchikken/cmake-js#6]
I am currently developing a website to visualize data coming from the particle collider (or similar data) for my last year of engineering school. To do that, I am looking at a way to create a module of the cern c++ code and integrate it to my nodeJS website.
Since the cern code (https://github.com/cbernet/albers-core based on https://root.cern.ch/drupal/content/downloading-root) is compiled with a CMakeLists.txt, I naturally found your cmake-js project really interesting. I tried your demo code and it worked flawlessly but I can't figure out how to make it work when the code used already have a CMakeLists.txt.

Here is the module project https://github.com/AmelieA/albers-core, I know it is not much but I don't know anything about cmake (apart from the doc I've read) and I am just trying to make the albers-core/examples/read.cc work with nodeJS without changing too much the architecture of the project (you can see that my code is almost only the files in the albers-core/javascript/ folder).

Here is the error code after an npm install : 

[ 94%] Building CXX object javascript/CMakeFiles/albers-read-adapter.dir/readAdapter.cc.o
ERR! OMG In file included from /home/amelie/workspace/albers-core-module-noSRC/javascript/readAdapter.cc:1:
ERR! OMG In file included from /home/amelie/workspace/albers-core-module-noSRC/node_modules/nan/nan.h:24:
ERR! OMG In file included from /home/amelie/.cmake-js/node-x64/v0.10.38/src/node.h:62:
ERR! OMG /home/amelie/.cmake-js/node-x64/v0.10.38/deps/v8/include/v8.h:3005:5: warning: anonymous types declared in an anonymous union are an extension [-Wnested-anon-types]
ERR! OMG     struct {
ERR! OMG     ^
ERR! OMG 1 warning generated.
ERR! OMG Linking CXX executable albers-read-adapter
ERR! OMG CMakeFiles/albers-read-adapter.dir/readAdapter.cc.o: In function `returnValue(v8::Arguments const&)':
ERR! OMG /home/amelie/workspace/albers-core-module-noSRC/javascript/readAdapter.cc:(.text+0x55d): undefined reference to `v8::HandleScope::HandleScope()'
ERR! OMG /home/amelie/workspace/albers-core-module-noSRC/javascript/readAdapter.cc:(.text+0x56e): undefined reference to `v8::Undefined()'
ERR! OMG /home/amelie/workspace/albers-core-module-noSRC/javascript/readAdapter.cc:(.text+0x576): undefined reference to `v8::Value::Uint32Value() const'
ERR! OMG /home/amelie/workspace/albers-core-module-noSRC/javascript/readAdapter.cc:(.text+0x57f): undefined reference to `v8::Number::New(double)'
ERR! OMG /home/amelie/workspace/albers-core-module-noSRC/javascript/readAdapter.cc:(.text+0x58b): undefined reference to `v8::HandleScope::RawClose(v8::internal::Object**)'
ERR! OMG /home/amelie/workspace/albers-core-module-noSRC/javascript/readAdapter.cc:(.text+0x597): undefined reference to `v8::HandleScope::~HandleScope()'
ERR! OMG /home/amelie/workspace/albers-core-module-noSRC/javascript/readAdapter.cc:(.text+0x5ac): undefined reference to `v8::HandleScope::~HandleScope()'
ERR! OMG CMakeFiles/albers-read-adapter.dir/readAdapter.cc.o: In function `InitAll(v8::Handle<v8::Object>)':
ERR! OMG /home/amelie/workspace/albers-core-module-noSRC/javascript/readAdapter.cc:(.text+0x5d4): undefined reference to `v8::String::New(char const*, int)'
ERR! OMG /home/amelie/workspace/albers-core-module-noSRC/javascript/readAdapter.cc:(.text+0x5e7): undefined reference to `v8::FunctionTemplate::New(v8::Handle<v8::Value> (*)(v8::Arguments const&), v8::Handle<v8::Value>, v8::Handle<v8::Signature>)'
ERR! OMG /home/amelie/workspace/albers-core-module-noSRC/javascript/readAdapter.cc:(.text+0x5ef): undefined reference to `v8::FunctionTemplate::GetFunction()'
ERR! OMG /home/amelie/workspace/albers-core-module-noSRC/javascript/readAdapter.cc:(.text+0x606): undefined reference to `v8::Object::Set(v8::Handle<v8::Value>, v8::Handle<v8::Value>, v8::PropertyAttribute)'
ERR! OMG clang-3.6: error: linker command failed with exit code 1 (use -v to see invocation)
ERR! OMG make[2]: *** [javascript/albers-read-adapter] Error 1
ERR! OMG make[1]: *** [javascript/CMakeFiles/albers-read-adapter.dir/all] Error 2
ERR! OMG make: *** [all] Error 2
ERR! OMG 

Any help is appreciated.
Amélie.

**Comment by unbornchikken** [comment]
First, you shouldn't pollute the C++ code that your module based on. Put your native dependencies in a deps folder. Then you can invoke it from your root CMakeLists.txt (which should be created like that you can find in CMake.js readme) just by adding its folder with [add_subdirectory](http://www.cmake.org/cmake/help/v3.0/command/add_subdirectory.html).

**Comment by AmelieA** [comment]
Ok, thanks, it seems like I'm getting somewhere.
But the build stops at the first include.

```
info CMD BUILD
info RUN cmake --build "/home/amelie/workspace/albers-core-module/build" --config Release
Scanning dependencies of target addon
[  3%] Building CXX object CMakeFiles/addon.dir/src/examples/write.cc.o
/home/amelie/workspace/albers-core-module/src/examples/write.cc:2:10: fatal error: 'datamodel/EventInfo.h' file not found
#include "datamodel/EventInfo.h"
         ^
1 error generated.
make[2]: *** [CMakeFiles/addon.dir/src/examples/write.cc.o] Error 1
make[1]: *** [CMakeFiles/addon.dir/all] Error 2
make: *** [all] Error 2
ERR! OMG Process terminated: 2 
```

I went to so what was wrong but I can't find anything.
The  SOURCE_FILES contain datamodel/EventInfo.h and the include_directories include /home/amelie/workspace/albers-core-module/src/datamodel'.

```
-- SOURCE_FILES = /home/amelie/workspace/albers-core-module/src/examples//write.cc;/home/amelie/workspace/albers-core-module/src/examples//read.cc;/home/amelie/workspace/albers-core-module/src/albers//Reader.cc;/home/amelie/workspace/albers-core-module/src/albers//CollectionBase.cc;/home/amelie/workspace/albers-core-module/src/albers//Registry.cc;/home/amelie/workspace/albers-core-module/src/albers//PyEventStore.cc;/home/amelie/workspace/albers-core-module/src/albers//Writer.cc;/home/amelie/workspace/albers-core-module/src/albers//EventStore.cc;/home/amelie/workspace/albers-core-module/src/javascript//readAdapter.cc;/home/amelie/workspace/albers-core-module/src/albers//Reader.h;/home/amelie/workspace/albers-core-module/src/albers//EventStore.h;/home/amelie/workspace/albers-core-module/src/albers//Writer.h;/home/amelie/workspace/albers-core-module/src/albers//LinkDef.h;/home/amelie/workspace/albers-core-module/src/albers//CollectionBase.h;/home/amelie/workspace/albers-core-module/src/albers//Registry.h;/home/amelie/workspace/albers-core-module/src/albers//PyEventStore.h;/home/amelie/workspace/albers-core-module/src/datamodel//src//EventInfoHandle.cc;/home/amelie/workspace/albers-core-module/src/datamodel//src//ParticleCollection.cc;/home/amelie/workspace/albers-core-module/src/datamodel//src//ParticleHandle.cc;/home/amelie/workspace/albers-core-module/src/datamodel//src//EventInfoCollection.cc;/home/amelie/workspace/albers-core-module/src/datamodel//datamodel//Particle.h;/home/amelie/workspace/albers-core-module/src/datamodel//datamodel//ParticleHandle.h;/home/amelie/workspace/albers-core-module/src/datamodel//datamodel//EventInfoCollection.h;/home/amelie/workspace/albers-core-module/src/datamodel//datamodel//EventInfo.h;/home/amelie/workspace/albers-core-module/src/datamodel//datamodel//LinkDef.h;/home/amelie/workspace/albers-core-module/src/datamodel//datamodel//EventInfoHandle.h;/home/amelie/workspace/albers-core-module/src/datamodel//datamodel//ParticleCollection.h;/home/amelie/workspace/albers-core-module/src/datamodel//datamodel//LorentzVector.h
-- CMAKE_SOURCE_DIR = /home/amelie/workspace/albers-core-module
-- Found ROOT: /home/amelie/Desktop/root/bin/root-config  
-- include_directories in examples folder = 
-- dir='/home/amelie/.cmake-js/node-x64/v0.10.38/src'
-- dir='/home/amelie/.cmake-js/node-x64/v0.10.38/deps/v8/include'
-- dir='/home/amelie/.cmake-js/node-x64/v0.10.38/deps/uv/include'
-- dir='/home/amelie/workspace/albers-core-module/node_modules/nan'
-- dir='/home/amelie/workspace/albers-core-module/src'
-- dir='/home/amelie/workspace/albers-core-module/build/src'
-- dir='/home/amelie/Desktop/root/include'
-- dir='/home/amelie/workspace/albers-core-module/src/datamodel'
-- include_directories in javascript folder = 
-- dir='/home/amelie/.cmake-js/node-x64/v0.10.38/src'
-- dir='/home/amelie/.cmake-js/node-x64/v0.10.38/deps/v8/include'
-- dir='/home/amelie/.cmake-js/node-x64/v0.10.38/deps/uv/include'
-- dir='/home/amelie/workspace/albers-core-module/node_modules/nan'
-- dir='/home/amelie/workspace/albers-core-module/src'
-- dir='/home/amelie/workspace/albers-core-module/build/src'
-- dir='/home/amelie/Desktop/root/include'
-- dir='/home/amelie/workspace/albers-core-module/src/datamodel'

```

**Comment by unbornchikken** [comment]
Created a PR. It builds. https://github.com/AmelieA/albers-core/pull/1

**Comment by AmelieA** [comment]
Thank you so much !

I've got a last question, why doesn't the module compile if the main project has cmake-js or nan as dependencies ?

**Comment by unbornchikken** [comment]
I dont get it, sorry. Can you show me exactly what doesn't compile?

**Comment by AmelieA** [comment]
If the main project has cmake-js as a dependency, you get: 
```
amelie@Samsung-550P7C ~/workspace/projetPFE $ npm install
|
> albers-core-module@1.0.0 install /home/amelie/workspace/projetPFE/node_modules/albers-core-module
> node ./node_modules/cmake-js/bin/cmake-js rebuild


module.js:340
    throw err;
          ^
Error: Cannot find module '/home/amelie/workspace/projetPFE/node_modules/albers-core-module/node_modules/cmake-js/bin/cmake-js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

If the main project has nan as a dependency, you get: 
```
info CMD BUILD
info RUN cmake --build "/home/amelie/workspace/projetPFE/node_modules/albers-core-module/build" --config Release
Scanning dependencies of target addon
[  5%] Building CXX object CMakeFiles/addon.dir/src/addon.cc.o
/home/amelie/workspace/projetPFE/node_modules/albers-core-module/src/addon.cc:2:10: fatal error: 'nan.h' file not found
#include <nan.h>
         ^
1 error generated.
make[2]: *** [CMakeFiles/addon.dir/src/addon.cc.o] Error 1
make[1]: *** [CMakeFiles/addon.dir/all] Error 2
make: *** [all] Error 2
ERR! OMG Process terminated: 2

```

But it works fine once your remove those dependencies.

**Comment by unbornchikken** [comment]
Grats, you've caught a bug! :) I'll fix it asap.

**Comment by unbornchikken** [comment]
It's there: https://github.com/unbornchikken/cmake-js/issues/7 I'm on it.

**Comment by unbornchikken** [comment]
Fixed in v0.11.4. For locating cmake-js correctly please use `cmake-js rebuild` as an install script in your module's package.json file. Readme and tutorials has been updated to reflect this.

Is there any further issues are you having or can I close this thread for good?

**Comment by AmelieA** [comment]
Well, I still can't use any function written in addon.cc yet and I don't know why. It seems like it does not find the function I'm calling but I can't see anything wrong with it.

Here is the error I'm getting: 
```
amelie@Samsung-550P7C ~/workspace/cmake-js-tut-01-test $ node app

/home/amelie/workspace/cmake-js-tut-01-test/app.js:53
console.log(addon.returnValue(4));
                  ^
TypeError: Object #<Object> has no method 'returnValue'
    at Object.<anonymous> (/home/amelie/workspace/cmake-js-tut-01-test/app.js:53:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

And addon.cc contain
```
NAN_METHOD(returnValue) {
  NanScope();
  int answer = args[0]->Uint32Value();
  NanReturnValue(NanNew<v8::Number>(answer));
}

void Init(v8::Handle<v8::Object> target) {
    target->Set(
          NanNew<v8::String>("returnValue")
        , NanNew<v8::FunctionTemplate>(returnValue)->GetFunction()
      );
}

NODE_MODULE(addon, Init)
```
I have also tried to use the old "void InitAll(Handle<Object> exports)" without success.



But it only happens after I changed "cmake-js-tut-01-module": "file:../cmake-js-tut-01-module" to "cmake-js-tut-01-module": "file:../albers-core-module" without deleting the node_modules folder beetwen the "npm install"
Otherwise, I just got the following message. But I can see that the module compiled and the node_modules/albers-core-module folder exist.

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'cmake-js-tut-01-module'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/amelie/workspace/cmake-js-tut-01-test/app.js:9:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by unbornchikken** [comment]
So, you've took my example application, replacted my tutorial module with yours, and you're getting the above errors? Am I right?

The second one is about you require cmake-js-tut-01-module but it has replaced so it doesn't available.

To get the whole picture, please push your addon to github and create a Gist containing your actual test application's app.js and package.json files.

**Comment by AmelieA** [comment]
Never mind, after writing everything properly, it works.
And by properly, i mean : 
"albers-core-module": "file:../albers-core-module" and not "cmake-js-tut-01-module": "file:../albers-core-module" in the package.json and var addon = require('albers-core-module'); in app.js.

I'll keep you updated if I've got problem with node-js written in coffeeScript and launched with grunt.
Thank you for the help !

**Comment by unbornchikken** [comment]
Np. I'm closing this then. Just open up another thread if you need any further assistance!
